### ISSUE TITLE
invalid disk size in terraform.tfstate after import

### ISSUE THREAD

**Issue by dvk1302dvk** [advancedhosting/terraform-provider-ah#27]
Hello.
When i  make ' terraform import  ah_cloud.server  ID' , the terraform.tfstate  have invalid record:
 ~ disk                     = 8192  on Smart-SX.
It's size of memory, sdd have size 80GB.
also 'image' and 'datacenter' not set correctly. = null

**Comment by punyabit** [comment]
Hi, @dvk1302dvk . Thanks for reporting! It seems like a bug in the cloud server import logic.  The new version v0.1.5 that includes fix has been released. Feel free to provide feedback
